### ISSUE TITLE
create README documentation

### ISSUE THREAD

**Issue by piyushhhxyz** [piyushhhxyz/StudyNotion-An-EdTech-Platform#1]
create a well structured Readme FIle , documenting the progress and features added and future features, 
Markdown

**Comment by distroaryan** [comment]
@piyushhhxyz Would like to work on this issue

**Comment by piyushhhxyz** [comment]
sure, please go ahead , assigning you this issue

**Comment by distroaryan** [comment]
@piyushhhxyz Thank you. Appreciate the opportunity

**Comment by piyushhhxyz** [comment]
Hope to see some impressive work @Aryan123-rgb 
here's the [Design File](https://www.figma.com/file/kEblNLyBFpLRbMpOg7GoaB/StudyNotion_shared-(Copy)?type=design&node-id=1-5&t=2zxfs0JB3ZYgwDy1-0) 
and here's the  [Project Description](https://docs.google.com/document/d/1dcZZlrqg3-GkPAkwuXiIu-q92ffiyvkI/edit?usp=sharing&ouid=110670960934920361748&rtpof=true&sd=true)

**Comment by piyushhhxyz** [comment]
@Aryan123-rgb  updates ?
